### ISSUE TITLE
oneAPI Compiler libimf.so  cannot open shared object file

### ISSUE THREAD

**Issue by kaanolgu** [ukri-excalibur/excalibur-tests#191]
I am testing oneAPI compilers on a custom environment and tried the steps at #156  but it still gives me the following error for the execution job file :

`omp-stream: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory`

```
- compiler:
    spec: oneapi@=2023.1.0
    paths:
      cc: /opt/software/pc2/EB-SW/software/intel-compilers/2023.1.0/compiler/2023.1.0/linux/bin/icx
      cxx: /opt/software/pc2/EB-SW/software/intel-compilers/2023.1.0/compiler/2023.1.0/linux/bin/icpx
      f77: /opt/software/pc2/EB-SW/software/intel-compilers/2023.1.0/compiler/2023.1.0/linux/bin/ifx
      fc: /opt/software/pc2/EB-SW/software/intel-compilers/2023.1.0/compiler/2023.1.0/linux/bin/ifx
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: 
      prepend_path:
        LD_LIBRARY_PATH: /opt/software/pc2/EB-SW/software/intel-compilers/2023.1.0/compiler/2023.1.0/linux/compiler/lib/intel64_lin
    extra_rpaths: 
    - /opt/software/pc2/EB-SW/software/intel-compilers/2023.1.0/compiler/2023.1.0/linux/compiler/lib/intel64_lin
 ```
    
 ```
$ ls /opt/software/pc2/EB-SW/software/intel-compilers/2023.1.0/compiler/2023.1.0/linux/compiler/lib/intel64_lin
cilk_db.so         libchkpwrap.a      libdecimal.a       libifcoremt.so.5   libifport.so.5     libiomp5.dbg       libirc.a           libistrconv.so     libqkmalloc.so     
crt/               libchkpwrap_h.a    libicaf.so         libifcore_pic.a    libimf.a           libiomp5_db.so     libirc_s.a         libmatmul.a        libsvml.a          
for_main.o         libchkpwrap_h_w.a  libifcore.a        libifcore.so       libimf.so          libiomp5.so        libirc.so          libpdbx.a          libsvml.so         
init.o             libchkpwrap_w.a    libifcoremt.a      libifcore.so.5     libintlc.so        libiompstubs5.a    libirng.a          libpdbxinst.a      locale/            
libbfp754.a        libcilkrts.so      libifcoremt_pic.a  libifport.a        libintlc.so.5      libiompstubs5.so   libirng.so         libpdbx.so         
libchkp.so         libcilkrts.so.5    libifcoremt.so     libifport.so       libiomp5.a         libipgo.a          libistrconv.a      libpdbx.so.5      
```
    
What could be the missing thing in here ?
