### ISSUE TITLE
Concretize spack environments separately

### ISSUE THREAD

**Issue by giordano** [ukri-excalibur/excalibur-tests#20]
Since we may need to install incompatible packages in the same environment, we should [concretize packages separately](https://spack.readthedocs.io/en/latest/environments.html#environments-concretization).  Note that we should also disable [views](https://spack.readthedocs.io/en/latest/environments.html#filesystem-views) to avoid conflicts, loosing views isn't a big deal for our use case.
```yaml
spack:
  concretization: separately
  view: false
```
